version: 2
updates:
  # Enable version updates for composer - main/web (new template)
  - package-ecosystem: composer
    directory: "/web"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "UTC"
    # Raise PRs for composer updates against the `main` branch
    target-branch: "main"
    reviewers:
      - Shopify/client-libraries-atc
    labels:
      - "Composer upgrades"
    open-pull-requests-limit: 100

  # Enable version updates for npm - main/ (new template)
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    # This will be CLI dependencies only
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "UTC"
    # Raise PRs for version updates to npm against the `main` branch
    target-branch: "main"
    reviewers:
      - Shopify/client-libraries-atc
    # Labels on pull requests for version updates only
    labels:
      - "npm dependencies"
